working_directory: /usr/src/app
netrc_filename: test_netrc
# operational value is ivo://cadc.nrc.ca/caom2repo
resource_id: ivo://cadc.nrc.ca/sc2repo
todo_file_name: todo.txt
# values True False
use_local_files: True
# values DEBUG INFO WARN ERROR
logging_level: INFO
# ad stream value - sorry
stream: raw
# how to control the work that gets done
# possible values are:
# - scrape - read the headers, write out the xml - kind of a test mode
# - store - calls cadc-data to put a file from local storage (use_local_files must be set to True)
# - ingest - read the headers, write the xml to the endpoint found by resource_id
# - enhance - create a footprint and previews for an existing CAOM model record
#
# these combinations have been tested:
# scrape => with use_local_files set to True
# scrape, enhance => with use_local_files set to True, will not write to service
#
# store, ingest, enhance => with use_local_files set to True
# ingest, enhance => with use_local_files set to True
#
# ingest, enhance => with use_local_files set to False
#
task_types: 
  - scrape
  - enhance
